USER=`whoami`
echo -e "\e[32m                 _..,rO@@hrr=====\e[0m."
echo -e "\e[32m            {kP''                 .e[0m."
echo -e "\e[32m         .i(                          j\      __.::^^^^::.. \e[0m"
echo -e "\e[32m        .n                             .-  +Z'                +h>' \e[0m"
echo -e "\e[32m        {         hey tester            O                          /_' \e[0m"
echo -e "\e[32m                                       .;                             _,. \e[0m"
echo -e "\e[32m        z                           ^./.                                 ?l \e[0m"
echo -e "\e[32m         +.                      I.C                                       ~. \e[0m"
echo -e "\e[32m           )l_               .+J  .-          $USER 어서오고                :: \e[0m"
echo -e "\e[32m              +asdllc~cJJu.=P    .r                                          ) \e[0m"
echo -e "\e[32m                   +r            .^           컴파일 얌전히 기다리리고       ~ \e[0m"
echo -e "\e[32m                   x             ..                                         II \e[0m"
echo -e "\e[32m                                  .~                                       Ii \e[0m"
echo -e "\e[32m                                    r:                                   j. \e[0m"
echo -e "\e[32m           ...I:;::;:;?ft             ).)                    rXvvvvXX}[ \e[0m"
echo -e "\e[32m         uI:;:;::;:::::::;{-             ilj............asdf.. \e[0m"
echo -e "\e[32m       .-:;::::;::;:;:;:;::;j;                            - .. \e[0m"
echo -e "\e[32m      I1:::;:;::;::::;:::;:::}-                            )...\e[0m"
echo -e "\e[32m      ?:;:;:::;::;:f;::;::;::;.                            ;!.     L}t++~+~_|C \e[0m"
echo -e "\e[32m      .l}:::?C::;?+  irz;::;::f                                 }{++~+~+~++~+~?m \e[0m"
echo -e "\e[32m      z;YUd.            .[::;:c                               1]+~+~+~+~+~+~+~++X \e[0m"
echo -e "\e[32m     z::Q                  >::|                              x+~+~+~+~+~+~+~+~+~~ \e[0m"
echo -e "\e[32m     ,:;Z                  j::>                             U+~+~+~+~+~+~+~+~+~++ \e[0m"
echo -e "\e[32m     ,::)    .   ^. :u.  c z:;}                             ++~+~+~+~+~+~+~+~+~+~ \e[0m"
echo -e "\e[32m    ,i:;:x     op   In+&   r::.                            z~+~+~+~+~+~+~+~+~+~+~ \e[0m"
echo -e "\e[32m     ,:::(^       j...     [;:c                            x+~+?Q+.@++~+~(@on+~+~ \e[0m"
echo -e "\e[32m  .r:;:;:}.    ^X .hbdx     d:81.   ~iZ^                   _~+~_wdt%k+~+c@aa~+~++ \e[0m"
echo -e "\e[32m  c::::;L      ^hbdbdbo      l::;^ .   ..               X~+~+~+~+~+Cw lr++~+~+~+~ \e[0m"
echo -e "\e[32m iI;:;:![        akkka       k:;<  v   ^[              .-~+~+~+~+~w     n~+~+~+~+ \e[0m"
echo -e "\e[32m _]:;::I<                    b:::C (   .[              L+~+~+~+~++J.    C~+~+~+~+ \e[0m"
echo -e "\e[32m  J>-:;:;n<W     .         Iwwxdi &    ^[              'r+~+~+~+~+~z?-C+~+~+~+~+~ \e[0m"
echo -e "\e[32m    w|L       )%o  qwq_?0h^  !+~.?.    ^[                f++~+~+~++~+~+~+~+~+~+~+ \e[0m"
echo -e "\e[32m            .no*bdbdbdbbdz             l                   n]+~+~+-jjkjf?~+~+~+f- \e[0m"
echo -e "\e[32m           ;%dbdbdbdbdbdbd&.          i                         in^ _  .{+~+~+~+~ \e[0m"
echo -e "\e[32m         ,}Xdbdbdbdbdbdbdbbo[      .);                        IvL+( ?  ^r~++~++~+ \e[0m"
echo -e "\e[32m       .u Udbdbdbdbdbdbdbddbbx  [~.                         ^n~-(+~f  ./++~+~+}+~ \e[0m"
echo -e "\e[32m      <? )bdbdbdbdbdbdbdbdbddbu                            _[~1{~+++~+~+~~+~+~]+~ \e[0m"
echo -e "\e[32m     i! Ihbdbdbdbdbdbdbdbdbbdb#                           z~+~Y+~+~~+~+~++~+~+[+~ \e[0m"
echo -e "\e[32m    Il  Qobdbdbdbdbdbdbdbdbdbddj                        ]r~+?X~+~+~+~+~+~+~+~+~q+ \e[0m"
echo -e "\e[32m   x   -qdbdbdbdbdbdbdbdbdbdbdbh                       r}~+~v+~+~+~++~+~+~+~+~+?j \e[0m"
echo -e "\e[32m   l  :-obdbdbdbdbdbdbdbdbdbdbddi                     /+~+~r+~+~+~+~+~+~+~+~+~+~| \e[0m"
echo -e "\e[32m   }<?.'Qbdbdbdbdbdbdbdbdbdbdbdb?                     ;~+~+v+~+~+~+~+~+~+~+~+~+~x \e[0m"
echo -e "\e[32m        Lbdbdbdbbdbdbdbdbdbdbdbo                     (z+~+~z~+~+~+~+~+~+~+~+~+~++ \e[0m"
echo -e "\e[32m         #bdbdbdbdbdbdbdbdbdbda                     r-~+~++n+~+~+~+~+~+~+~+~+~+~+ \e[0m"
echo -e "\e[32m         ,pdbdbdbdbdbdbdbdbdbo'                    -(++~+~~zb1~+~+~+~+~+~+~++~+~+ \e[0m"
echo -e "\e[32m           f8kbdbdbdbdbbdbdCI                      v+~+~+fl _~+~++~++~+~++~+~+~+~ \e[0m"
echo -e "\e[32m           ?   'II/BBBd:I' ^                       m/}~-}  v++~+~+~+~+~+~+~+~+~+~ \e[0m"
echo -e "\e[32m           /          I   i                                -~+~+~+~+~+~+~+~+~+~++ \e[0m"
echo -e "\e[32m           f          f   8                                I~+~+~+~+~+~+~+~+~+~+~ \e[0m"
echo -e "\e[32m           1          z   p                                1 .  .  .':;;:;;::   . \e[0m"

bash launch.sh > result.txt
cat result.txt

echo -e "\e[32m.__                       __                   __\e[0m"
echo -e "\e[32m|  |__   ____ ___.__.   _/  |_  ____   _______/  |_  ___________\e[0m"
echo -e "\e[32m|  |  \ /  _ <   |  |   \   __\/ __ \ /  ___/\   __\/ __ \_  __ \ \e[0m"
echo -e "\e[32m|   Y  (  <_> )___  |    |  | \  ___/ \___ \  |  | \  ___/|  | \/\e[0m"
echo -e "\e[32m|___|  /\____// ____|____|__|  \___  >____  > |__|  \___  >__|\e[0m"
echo -e "\e[32m     \/       \/   /_____/         \/     \/            \/\e[0m"
rm a.out
